Project4.exe: Node.h LinkedList.h Controller.o main.cpp
		g++ Node.h LinkedList.h Controller.o main.cpp -o Project4.exe

Controller.o: Controller.h Controller.cpp
		g++ -c Controller.h Controller.cpp


