Project5.exe: main.cpp Dictionary.h Dictionary.cpp DictionaryNode.h DictionaryUI.h DictionaryUI.cpp Word.h Word.cpp
		g++ main.cpp Dictionary.h Dictionary.cpp DictionaryNode.h DictionaryUI.h DictionaryUI.cpp Word.h Word.cpp -o Project5.exe
